# Production overrides
spring.thymeleaf.cache=true
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
logging.level.root=INFO
logging.level.com.sureprompt=INFO

# Mandatory Secure Injection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

app.jwt.secret=${JWT_SECRET}
app.aes.secret=${SUREPROMPT_AES_KEY}
gemini.api.key=${GEMINI_API_KEY}
